### ISSUE TITLE
Option to list the instruments

### ISSUE THREAD

**Issue by Morwenn** [Aearnus/cherchord#5]
It would be nice to have an option to list the available instruments and the corresponding notes directly from the command line.

**Comment by DataKinds** [comment]
Thanks for creating this issue! Instruments are currently displayed in the help menu of the app, accessed with the `-h/--help` flag. This, however, made me notice that the help flag is not mentioned on the usage screen. This has been fixed in f603f33cad3ed3e1863d296161eac6eddd584fce. The help screen is now displayed by default if no arguments are provided.
